<?php
// ===================================================================
// Database Connection File
// This is the "Database Layer" of the three tier architecture.
// Every page that needs the database will include this file.
// ===================================================================

// Change these settings if your XAMPP setup is different
$db_host = "localhost";
$db_user = "root";
$db_pass = "";
$db_name = "student_routine_organizer";

mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);

try {
    // Create the connection using mysqli (procedural style).
    $conn = mysqli_connect($db_host, $db_user, $db_pass, $db_name);

    // Store and retrieve all application text as full UTF-8.
    mysqli_set_charset($conn, "utf8mb4");

    // Keep timestamps generated by this MySQL connection aligned with Malaysia time.
    mysqli_query($conn, "SET time_zone = '+08:00'");
} catch (mysqli_sql_exception $exception) {
    $log_message = str_replace(array("\r", "\n"), " ", $exception->getMessage());
    error_log(
        "[Database connection] mysqli error "
        . (int) $exception->getCode()
        . ": "
        . $log_message
    );

    // Keep connection details and internal exception information away from users.
    die("Sorry, we could not connect to the database right now. Please try again later.");
}
?>
